name: bps_portal_marketing
version: 1.13.30+11330
publish_to: 'none'
description: "BPS Portal Marketing project."
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  animations: ^2.0.11
  awesome_snackbar_content: ^0.1.4
  camera: ^0.11.0+2
  carousel_slider: ^5.0.0
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.2
  device_info_plus: ^10.1.0
  equatable: ^2.0.5
  external_path: ^1.0.3
  firebase_analytics: ^10.10.5
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.14
  firebase_messaging: ^14.9.4
  firebase_remote_config: ^4.4.5
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.7+1
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_speed_dial: ^7.0.0
  fluttertoast: ^8.2.4
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_maps_flutter: ^2.5.3
  iconsax: ^0.0.8
  infinite_scroll_pagination: ^4.0.0
  intl: any
  lint: ^2.3.0
  location: ^6.0.2
  logger: ^2.0.2+1
  media_scanner: ^2.1.0
  media_store_plus: ^0.1.3
  package_info_plus: ^8.0.0
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  photo_manager: ^3.0.0
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  simple_connection_checker: ^0.2.1
  timezone: ^0.9.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  widgets_to_image: ^0.0.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - env/
