import 'package:get/get.dart';

class Strings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'id': {
          "app-name-text": "Portal Marketing",
          "current-lang-text": "Bahasa: %s",
          "change-lang-text": "Ubah bahasa",
          "user-profile-text": "Profil pengguna",
          "need-access-text": "Kita butuh akses!",
          "need-access-desc-text":
              "Untuk melanjutkan menggunakan aplikasi ini, Anda harus memberikan akses ke Kamera, Galeri dan Lokasi",
          "camera-access-text": "Akses Kamera",
          "camera-access-desc-text":
              "Kita memerlukan akses ke kamera untuk mengambil foto",
          "mic-access-text": "Akses Mikrofon",
          "mic-access-desc-text":
              "Kita memerlukan akses ke mikropon untuk merekam suara",
          "location-access-text": "Akses Lokasi",
          "location-access-desc-text":
              "Kita memerlukan akses ke lokasi untuk mengambil alamat melalui GPS",
          "photo-lib-access-text": "Akses Galeri",
          "photo-lib-access-desc-text":
              "Kita memerlukan akses ke galeri untuk menampilkan foto yang sudah Anda ambil",
          "open-settings-text": "Buka Pengaturan",
          "next-text": "Lanjut",
          "permission-needed-text": "Izin diperlukan: %s",
          "choose-folder-text": "Pilih Folder",
          "save-ori-photos-text": "Simpan Foto Asli",
          "photo-preview-text": "DCIM/BPS_Portal_Kamera/",
          "save-text": "Simpan",
          "share-text": "Bagikan",
          "delete-text": "Hapus",
          "save-image-success-text": "Gambar berhasil disimpan",
          "save-image-failed-text": "Tidak bisa menyimpan gambar",
          "convert-image-failed-text": "Gagal mengkonversi gambar",
          "set-photo-dir-failed-text": "Gagal set direktori foto",
          "watermark-text": "Watermark",
          "sd-card-permission-text": "Akses Kartu SD",
          "language-text": "Bahasa",
          "version-text": "Versi",
          "get-premium-text": "Dapatkan Premium",
          "upgrade-text": "Tingkatkan",
          "custom-file-text": "Nama File Kustom",
          "press-back-button-text": "Tekan sekali lagi untuk keluar",
          "dt-text": "Tanggal & Waktu",
          "sequence-number-text": "Nomor Urut",
          "custom-name-text": "Nama Kustom @number",
          "hms-text": "Jam Menit Detik",
          "day-text": "Hari",
          "24-hour-text": "24 Jam",
          "captured-by-text": "OlehBPSPortalKamera",
          "full-text": "Penuh",
          "off-text": "Mati",
          "3s-text": "3dtk",
          "5s-text": "5dtk",
          "10s-text": "10dtk",
          "error-text": "Terjadi kesalahan, harap hubungi Admin",
          "error-try-text": "Terjadi kesalahan, harap ulangi lagi",
          "del-confirm-text": "Apakah Anda yakin ingin menghapus foto ini?",
          "del-success-text": "Foto berhasil dihapus",
          "del-fail-text": "Foto gagal dihapus",
          "confirm-title-text": "Konfirmasi",
          "cancel-text": "Batalkan",
          "ok-text": "OK",
          "no-text": "Tidak",
          "add-another-question-text": "Ingin menambahkan data lain?",
          "photo-not-found-text": "Foto tidak ditemukan",
          "no-photo-found-text": "Tidak ada foto",
          "photo-visit-text": "Foto Kunjungan",
          "add-contact-text": "Tambah Kontak",
          "add-address-text": "Tambah Alamat",
          "add-group-text": "Tambah Grup",
          "coming-soon-text": "Coming soon...",
          "min-password-text": "Kata Sandi setidaknya @length karakter.",
          "success-text": "Sukses!",
          "whoops-text": "Whoops!",
          "username-text": "Username",
          "password-text": "Kata Sandi",
          "password-confirmation-text": "Konfirmasi Kata Sandi",
          "email-text": "Surel",
          "phone-text": "Nomor Telepon",
          "role-text": "Jabatan",
          "forgot-password-text": "Lupa kata sandi?",
          "login-text": "Masuk",
          "logout-text": "Keluar",
          "welcome-back-text": "Selamat datang 👋",
          "to-text": "di",
          "hello-login-text": "Halo, silakan masuk untuk melanjutkan",
          "hello-register-text": "Halo, silakan buat akun terlebih dahulu",
          "live-gold-price-text": "Harga Emas Live",
          "last-update-text": "Terakhir diperbarui:",
          "connection-error-text": "Koneksi bermasalah 😓",
          "check-connection-text": "Harap periksa koneksi Anda.",
          "module-visit-name-text": "Modul Visit",
          "module-telemarketing-name-text": "Modul Telemarketing",
          "usd-to-idr-text": "Kurs Dollar",
          "pricing-text": "Daftar Harga",
          "refresh-text": "Perbarui sekarang",
          "dont-have-account-text": "Belum punya akun?",
          "have-account-text": "Sudah punya akun?",
          "register-text": "Daftar",
          "required-field-text": "@field dibutuhkan",
          "invalid-field-text": "@field tidak benar",
          "not-match-field-text": "@field tidak sama",
          "find-customer-text": "Cari pelanggan...",
          "find-contact-text": "Cari kontak...",
          "find-store-contact-location-customer-text":
              "Cari toko/nama/lokasi pelanggan...",
          "find-text": "Cari @string...",
          "store-text": "Toko",
          "invoice-text": "Nomor invoice",
          "name-text": "Nama",
          "receiver-name-text": "Nama Penerima",
          "type-text": "Tipe",
          "group-text": "Grup",
          "address-text": "Alamat",
          "contact-text": "Kontak",
          "map-or-region-text": "Peta / Wilayah",
          "province-text": "Provinsi",
          "city-text": "Kota / Kabupaten",
          "suburb-text": "Kecamatan",
          "area-text": "Kelurahan",
          "loading-text": "Harap tunggu...",
          "total-text": "Total @field",
          "empty-data-text": "Tidak ada data.",
          "someone-address-text": "Alamat @name",
          "follow-up-text": "Follow Up",
          "latest-follow-up-text": "Follow Up Terakhir",
          "latest-purchase-text": "Pembelian Terakhir",
          "purchase-text": "Pembelian",
          "customer-text": "Pelanggan",
          "unknown-text": "Tidak Diketahui",
          "see-more-text": "Lihat selengkapnya",
          "follow-up-count-text": "Jumlah Follow Up: @number",
          "all-text": "Semua",
          "mine-text": "Saya",
          "filter-text": "Filter",
          "filter-used-text": "Beberapa filter digunakan",
          "show-all-text": "Tampilkan semua",
          "all-customer-text": "Semua pelanggan",
          "date-text": "Tanggal",
          "today-text": "Hari ini",
          "last-n-days-text": "@number hari terakhir",
          "custom-text": "Kustom",
          "display-text": "Menampilkan",
          "your-text": "Milikmu",
          "latest-text": "Terbaru",
          "of-data-text": "Data",
          "that-contains-text": "Yang mengandung",
          "selected-text": "Dipilih",
          "apply-text": "Terapkan",
          "response-text": "Respon",
          "brand-text": "Merk",
          "add-response-text": "Tambah Respon",
          "sales-text": "Penjualan",
          "note-text": "Catatan: @string",
          "retry-text": "Muat ulang",
          "another-stuff-text": "dan @count barang lainnya",
          "stuff-text": "Barang",
          "custom-value-text": "@value",
          "status-text": "Status",
          "potential-text": "Potensial",
          "not-potential-text": "Tidak Potensial",
          "n-a-text": "N/A",
          "reminder-text": "Pengingat",
          "reminder-desc-text":
              "Menampilkan pelanggan yang belum difollow-up selama lebih dari 30 hari.",
          "failed-open-camera-text": "Gagal membuka kamera",
          "sales-1-text": "Sales 1",
          "sales-2-text": "Sales 2",
          "visit-date-text": "Tanggal kunjungan",
          "note-field-text": "Catatan",
          "add-visit-text": "Tambah Kunjungan",
        },
        'en': {
          "app-name-text": "Portal Marketing",
          "current-lang-text": "Language: %s",
          "user-profile-text": "User profile",
          "change-lang-text": "Change language",
          "need-access-text": "We need some access!",
          "need-access-desc-text":
              "You need to grant access to the device camera, Photo Library and Location to take photos or record video",
          "camera-access-text": "Camera Access",
          "camera-access-desc-text":
              "App needs access to your camera for capture photo & stamp on photo",
          "mic-access-text": "Microphone Access",
          "mic-access-desc-text":
              "App needs access to your microphone for record audio",
          "location-access-text": "Location Access",
          "location-access-desc-text":
              "App needs access to your location for display current location",
          "photo-lib-access-text": "Photo Library Access",
          "photo-lib-access-desc-text":
              "App needs access to your photo library for brows your albums",
          "open-settings-text": "Open Settings",
          "next-text": "Next",
          "permission-needed-text": "Permission needed: %s",
          "choose-folder-text": "Choose Folder",
          "save-ori-photos-text": "Save Original Photos",
          "photo-preview-text": "DCIM/Kamera GPS Lokasi/",
          "save-text": "Save",
          "share-text": "Share",
          "delete-text": "Delete",
          "save-image-success-text": "Image saved successfully",
          "save-image-failed-text": "Unable to save image",
          "convert-image-failed-text": "Unable to convert image",
          "set-photo-dir-failed-text": "Unable to set photo directory",
          "watermark-text": "Watermark",
          "sd-card-permission-text": "SD Card Permission",
          "language-text": "Language",
          "version-text": "Version",
          "get-premium-text": "Get Premium",
          "upgrade-text": "Upgrade",
          "custom-file-text": "Custom File Name",
          "press-back-button-text": "Press back one more time to exit",
          "dt-text": "Date & Time",
          "sequence-number-text": "Sequence Number",
          "custom-name-text": "Custom Name @number",
          "hms-text": "Hour Minute Second",
          "day-text": "Day",
          "24-hour-text": "24 Hour",
          "captured-by-text": "OlehBPSPortalKamera",
          "full-text": "Full",
          "off-text": "Off",
          "3s-text": "3s",
          "5s-text": "5s",
          "10s-text": "10s",
          "error-text": "Something went wrong, please contact Admin",
          "error-try-text": "Something went wrong, please try again",
          "del-confirm-text": "Are you sure want to delete this photo?",
          "del-success-text": "Photo deleted",
          "del-fail-text": "Unable to delete photo",
          "confirm-title-text": "Confirmation",
          "cancel-text": "Cancel",
          "ok-text": "OK",
          "no-text": "No",
          "add-another-question-text": "Add another?",
          "photo-not-found-text": "Photo not found",
          "no-photo-found-text": "No photo",
          "photo-visit-text": "Photo of Visit",
          "add-contact-text": "Add Contact",
          "add-address-text": "Add Address",
          "add-group-text": "Add Group",
          "coming-soon-text": "Coming soon...",
          "min-password-text":
              "Password should be at least @length characters length.",
          "success-text": "Success!",
          "whoops-text": "Whoops!",
          "username-text": "Username",
          "password-text": "Password",
          "password-confirmation-text": "Password Confirmation",
          "email-text": "Email",
          "phone-text": "Phone Number",
          "role-text": "Role",
          "forgot-password-text": "Forgot password?",
          "login-text": "Login",
          "logout-text": "Logout",
          "welcome-back-text": "Welcome back 👋",
          "to-text": "to",
          "hello-login-text": "Hello there, login to continue",
          "hello-register-text": "Hello there, please register an account",
          "live-gold-price-text": "Live Gold Price",
          "last-update-text": "Last update:",
          "connection-error-text": "Connection error 😓",
          "check-connection-text": "Please check your connection.",
          "module-visit-name-text": "Module Visit",
          "module-telemarketing-name-text": "Module Telemarketing",
          "usd-to-idr-text": "Dollar Exchange Rate",
          "pricing-text": "Pricing",
          "refresh-text": "Refresh",
          "dont-have-account-text": "Don't have an account?",
          "have-account-text": "Already have an account?",
          "register-text": "Register",
          "required-field-text": "@field required",
          "invalid-field-text": "Invalid @field",
          "not-match-field-text": "@field doesn't match",
          "find-customer-text": "Find customer...",
          "find-contact-text": "Find contact...",
          "find-store-contact-location-customer-text":
              "Find customer's store/name/location...",
          "find-text": "Find @string...",
          "store-text": "Store",
          "invoice-text": "Invoice",
          "name-text": "Name",
          "receiver-name-text": "Receiver Name",
          "type-text": "Type",
          "group-text": "Group",
          "address-text": "Address",
          "contact-text": "Contact",
          "map-or-region-text": "Map / Region",
          "province-text": "Province",
          "city-text": "City",
          "suburb-text": "Suburb",
          "area-text": "Area",
          "loading-text": "Loading...",
          "total-text": "Total @field",
          "empty-data-text": "No data found.",
          "someone-address-text": "@name Address",
          "follow-up-text": "Follow Up",
          "latest-follow-up-text": "Latest Follow Up",
          "latest-purchase-text": "Latest Purchase",
          "purchase-text": "Purchase",
          "customer-text": "Customer",
          "unknown-text": "Unknown",
          "see-more-text": "See more",
          "follow-up-count-text": "Total Follow Up: @number",
          "all-text": "All",
          "mine-text": "Mine",
          "filter-text": "Filter",
          "filter-used-text": "Multiple filter are used",
          "show-all-text": "Show all",
          "all-customer-text": "All customers",
          "date-text": "Date",
          "today-text": "Today",
          "last-n-days-text": "Last @number days",
          "custom-text": "Custom",
          "display-text": "Display",
          "your-text": "Your",
          "latest-text": "Latest",
          "of-data-text": "Of data",
          "that-contains-text": "That contains",
          "selected-text": "Selected",
          "apply-text": "Apply",
          "response-text": "Response",
          "brand-text": "Brand",
          "add-response-text": "Add Response",
          "sales-text": "Sales",
          "note-text": "Note: @string",
          "retry-text": "Retry",
          "another-stuff-text": "and @count others",
          "stuff-text": "Stuff",
          "custom-value-text": "@value",
          "status-text": "Status",
          "potential-text": "Potential",
          "not-potential-text": "Not Potential",
          "n-a-text": "N/A",
          "reminder-text": "Reminder",
          "reminder-desc-text":
              "Displays customers who have not been followed up for more than 30 days.",
          "failed-open-camera-text": "Unable to start camera",
          "sales-1-text": "Sales 1",
          "sales-2-text": "Sales 2",
          "visit-date-text": "Visit date",
          "note-field-text": "Note",
          "add-visit-text": "Add Visit",
        },
      };
}
